stages:
    - test

.test-common:
    stage: test
    cache:
        key: dav1d.git-20200110
        paths:
            - cache/dav1d.git/
    before_script:
        - test -d cache || mkdir cache
        - test -d cache/dav1d.git && GIT_DIR=cache/dav1d.git git fetch --refmap=refs/heads/master:refs/heads/master origin master
        - test -d cache/dav1d.git || git clone --bare https://code.videolan.org/videolan/dav1d.git cache/dav1d.git
        - git clone cache/dav1d.git dav1d
        - git -C dav1d describe --always --long
        - ln -sf $(pwd) dav1d/tests/dav1d-test-data
    script:
        - meson setup build dav1d --buildtype release
                                  -Dtestdata_tests=true
                                  -Dlogging=false
        - ninja -C build
        - cd build && time meson test -v
    dependencies: []

test-debian:
    extends: .test-common
    image: registry.videolan.org/dav1d-debian-unstable:20230213200113
    tags:
        - docker
        - amd64

test-debian-aarch64:
    extends: .test-common
    image: registry.videolan.org/dav1d-debian-bullseye-aarch64:20230211050329
    tags:
        - docker
        - aarch64

test-debian-ppc64le:
    extends: .test-common
    image: registry.videolan.org/dav1d-debian-unstable-ppc64le:20230211050439
    tags:
        - docker
        - ppc64le

test-debian-armv7-clang-5:
    extends: .test-common
    image: registry.videolan.org/dav1d-debian-bullseye-armv7:20230211045904
    tags:
        - docker
        - armv7
    variables:
        CC: clang-5.0
        CFLAGS: '-integrated-as'
    script:
        - linux32 meson setup build dav1d --buildtype release
                                          -Dtestdata_tests=true
                                          -Dlogging=false
        - ninja -C build
        - cd build && time meson test -v
